USE DATABASE battery;

CREATE TABLE uploadedFile(
    fileID INTEGER PRIMARY KEY AUTO_INCREMENT,
    typeNum TEXT NOT NULL,
    uploadTime TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE cycle_capacity(
    cycleID INTEGER PRIMARY KEY AUTO_INCREMENT,
    fileID INTEGER NOT NULL,
    cycleNum INTEGER NOT NULL,
    capacity DECIMAL(20, 15) NOT NULL,
    FOREIGN KEY (fileID) REFERENCES uploadedFile(fileID)
);

CREATE TABLE cycle_data(
    TCVID INTEGER PRIMARY KEY AUTO_INCREMENT,
    cycleTime DECIMAL(10, 1) NOT NULL,
    current DECIMAL(20, 15) NOT NULL,
    voltage DECIMAL(20, 15) NOT NULL,
    fileID INTEGER NOT NULL,
    cycleNum INTEGER NOT NULL,
    FOREIGN KEY (fileID) REFERENCES uploadedFile(fileID)
);
